---
output:
  pdf_document: default
  html_document: default
---
# Explore the relationship between transit time and number of commutes for subways and roads

```{r}
library(tidyverse)
```

```{r}
driving <- readr::read_csv('data/nta-driving-weights.csv')
subway <- readr::read_csv('data/nta-subway-weights.csv')
transfers <- readr::read_csv('data/nta-subway-transfers.csv')
walking <- readr::read_csv('data/nta-walking-weights.csv')
```

## Driving plot
### Driving 
```{r}
ggplot(data = driving, aes(x = seconds_in_traffic**(1/4), y = log(S000))) +
  geom_point() +
  stat_smooth()
```

### Driving Inverse
```{r}
ggplot(data = driving, aes(x = 1 / seconds_in_traffic^(1/8), y = log(S000))) +
  geom_point() +
  stat_smooth()
```

## Driving model
### Driving 
```{r}
quarter_seconds <- driving$seconds_in_traffic^(1/4)
driving_model <- lm(log(driving$S000) ~ quarter_seconds)
summary(driving_model)
```

### Driving inverse
```{r}
i_quarter_seconds <- 1 /  driving$seconds_in_traffic^(1/8)
i_driving_model <- lm(log(driving$S000) ~ i_quarter_seconds)
summary(i_driving_model)
```

```{r}
plot(i_driving_model)
```

## Subway
```{r}
ggplot(data = subway, aes(x = seconds_in_transit^(1/2), y = log(S000))) +
  geom_point() +
  stat_smooth()
```

```{r}
subway_model <- lm(log(subway$S000) ~ sqrt(subway$seconds_in_transit))
summary(subway_model)
```
```{r}
plot(subway_model)
```

```{r}
i_seconds_in_transt <- 1 / (subway$seconds_in_transit^(1 / 8))
i_subway_model <- lm(log(subway$S000) ~ i_seconds_in_transt)
summary(i_subway_model)
```

```{r}
plot(i_subway_model)
```


```{r}
subway_and_driving_model <- lm(log(subway$S000) ~ subway$seconds_in_transit + driving$seconds_in_traffic)
summary(subway_and_driving_model)
```

```{r}
summary(subway$seconds_in_transit)

summary(driving$seconds_in_traffic)
```
## walking
```{r}
ggplot(data = walking, aes(x = seconds_of_walking, y = S000)) +
  geom_point() +
  stat_smooth()
```

```{r}
ggplot(data = walking, aes(x = 1 / seconds_of_walking^(1/8), y = log(S000))) +
  geom_point() +
  stat_smooth()
```
```{r}
i_walking_time <- 1 / walking$seconds_of_walking^(1 / 8)
i_walking_model <- lm(log(walking$S000) ~ i_walking_time)
summary(i_walking_model)
```
## Transfers
```{r}
print(transfers)
summary(transfers)
```

```{r}
transfers_cat <- transfers %>%
  dplyr::mutate(line_nom = as.character(line_count))
```

```{r}
ggplot(data = transfers_cat, aes(x = line_nom, y = S000)) +
  geom_boxplot()
```

```{r}
ggplot(data = transfers_cat, aes(x = line_nom, y = log(S000))) +
  geom_boxplot()
```

## Plot the model equations
```{r}
i_walking_eq <- function(x) exp(-1.9091 + 20.8372 / x^(1 / 8))
i_driving_eq <- function(x) exp(-1.9856 + 17.9177 / x^(1 / 8))
i_subway_eq <- function(x) exp(-3.4558 + 23.4092 / x^(1 / 8))

ggplot(
  data.frame(
    seconds = seq(from = 301, to = 15100, by = 14.8)
    )
  , aes(seconds)) +
  stat_function(fun = i_walking_eq, color = "blue", xlim = c(701, 15171)) +
  stat_function(fun = i_driving_eq, color = "red", xlim = c(276, 3122)) +
  stat_function(fun = i_subway_eq, color = "green", xlim = c(645, 6924))

ggplot(
  data.frame(
    seconds = c(701, 3122)
    )
  , aes(seconds)) +
  stat_function(fun = i_walking_eq, color = "blue") +
  stat_function(fun = i_driving_eq, color = "red") +
  stat_function(fun = i_subway_eq, color = "green")

ggplot(
  data.frame(
    seconds = c(1200, 2400)
    )
  , aes(seconds)) +
  stat_function(fun = i_walking_eq, color = "blue") +
  stat_function(fun = i_driving_eq, color = "red") +
  stat_function(fun = i_subway_eq, color = "green")
```

## Subway remove points with no connections
```{r}
f_i_subway <- subway %>%
  dplyr::left_join(transfers) %>%
  dplyr::filter(line_count > 0) %>%
  dplyr::mutate(
    log_S000 = log(S000),
    i_seconds = 1 / seconds_in_transit^(1/8)
  )
```

```{r}
ggplot(f_i_subway, aes(i_seconds, log_S000)) +
  geom_point() +
  stat_smooth()
```

```{r}
f_i_subway_model <- lm(f_i_subway$log_S000 ~ f_i_subway$i_seconds)
summary(f_i_subway_model)
```

```{r}
f_i_subway_eq <- function(x) exp(-3.0033 + 22.1264 / x^(1 / 8))
```

```{r}
ggplot(
  data.frame(
    seconds = seq(from = 301, to = 15100, by = 14.8)
    )
  , aes(seconds)) +
  stat_function(fun = i_walking_eq, color = "blue", xlim = c(701, 15171)) +
  stat_function(fun = i_driving_eq, color = "red", xlim = c(276, 3122)) +
  stat_function(fun = f_i_subway_eq, color = "green", xlim = c(645, 6924))
```

```{r}
ggplot(
  data.frame(
    seconds = c(701, 3122)
    )
  , aes(seconds)) +
  stat_function(fun = i_walking_eq, color = "blue") +
  stat_function(fun = i_driving_eq, color = "red") +
  stat_function(fun = f_i_subway_eq, color = "green")
```

```{r}
ggplot(
  data.frame(
    seconds = c(1200, 2400)
    )
  , aes(seconds)) +
  stat_function(fun = i_walking_eq, color = "blue") +
  stat_function(fun = i_driving_eq, color = "red") +
  stat_function(fun = f_i_subway_eq, color = "green")
```