# Auto-correlation and regression for Queen's contiguity at neighborhood tabulation area resolution

```{r, message = FALSE}
library(sf)
library(tidyverse)
library(tmap)
library(spdep)
options(scipen = 999)
```

```{r, message = FALSE}
bk_name <- "Brooklyn"
bk_county_code <- "047"
bk_parks <- "BK99"

bk_nta_borders <- sf::st_read('./data/nyc_2010_nta_borders.geojson') %>%
  dplyr::filter(BoroName == bk_name)  %>%
  dplyr::filter(NTACode != bk_parks) %>%
  dplyr::select("NTACode", "Shape__Area", "Shape__Length", "geometry")

bk_od_tract <- readr::read_csv("./data/ny_od_main_JT00_2019.csv") %>%
  dplyr::filter(
      stringr::str_sub(as.character(w_geocode), 3, 5) == bk_county_code &
      stringr::str_sub(as.character(h_geocode), 3, 5) == bk_county_code
  ) %>%
  dplyr::mutate(
   w_tract = stringr::str_sub(as.character(w_geocode), 6, 11)
  ) %>%
  dplyr::mutate(
   h_tract = stringr::str_sub(as.character(h_geocode), 6, 11)
  ) %>%
  dplyr::select("w_tract", "h_tract", "S000")
```
```{r, message=FALSE}
bk_tract_nta_equiv <- readxl::read_xlsx('./data/nyc_2010_census_tract_nta_equiv.xlsx') %>%
  dplyr::filter(borough_name == bk_name) %>%
  dplyr::filter(nta_code != bk_parks) %>%
  dplyr::rename(tract = census_tract) %>%
  dplyr::select("tract", "nta_code")

bk_od <- bk_od_tract %>%
  dplyr::left_join(bk_tract_nta_equiv, c("w_tract" = "tract")) %>%
  dplyr::rename(w_nta_code = nta_code) %>%
  dplyr::left_join(bk_tract_nta_equiv, c("h_tract" = "tract")) %>%
  dplyr::rename(h_nta_code = nta_code) %>%
  dplyr::select("h_nta_code", "w_nta_code", "S000") %>%
  dplyr::filter(w_nta_code != bk_parks & h_nta_code != bk_parks)
```

```{r, message=FALSE}
bk_dest <- bk_od %>%
  dplyr::group_by(w_nta_code) %>%
  dplyr::summarise(
    S000 = sum(S000)
  ) %>%
  unique()

bk_dest_borders <- bk_dest %>%
  dplyr::left_join(bk_nta_borders, c("w_nta_code" = "NTACode")) %>%
  sf::st_as_sf()

tmap::tm_shape(bk_dest_borders) +
  tmap::tm_polygons(
    col = "S000",
    style = "jenks",
    title = "Count"
  ) + tmap::tm_layout(
    title = "Jobs in each nta",
    legend.outside = TRUE
  )
```

### Moran's I Test: Global analysis
```{r, message=FALSE}
bk_nta_neighbor_weights <- bk_dest_borders %>%
  spdep::poly2nb(c("w_nta_code")) %>%
  spdep::nb2listw(zero.policy = TRUE)

bk_global_moran <- bk_nta_neighbor_weights %>%
  spdep::moran.test(bk_dest_borders$S000, ., zero.policy = TRUE)

bk_global_moran
```

```{r, message=FALSE}
spdep::moran.plot(
  bk_dest_borders$S000,
  bk_nta_neighbor_weights,
  zero.policy = TRUE,
  xlab = "Job count",
  ylab = "Lagged job count",
  pch = 20,
)
```

### Local indicators of spatial autocorrelation
```{r, message=FALSE}
bk_lisa <- spdep::localmoran(
  bk_dest_borders$S000,
  bk_nta_neighbor_weights,
  zero.policy = TRUE,
  na.action = na.omit,
)

sig_lev <- 0.05
avg_jobs <- mean(bk_dest_borders$S000)

bk_lisa_classes <- bk_lisa %>%
  tibble::as_tibble() %>%
  magrittr::set_colnames(
    c("Ii","E.Ii","Var.Ii","Z.Ii","Pr(z > 0)")
  ) %>%
  dplyr::mutate(
    coType = dplyr::case_when(
      `Pr(z > 0)` > 0.05 ~ "Insignificant",
      `Pr(z > 0)` <= 0.05 & Ii >= 0 & bk_dest_borders$S000 >= avg_jobs ~ "HH",
      `Pr(z > 0)` <= 0.05 & Ii >= 0 & bk_dest_borders$S000 <  avg_jobs ~ "LL",
      `Pr(z > 0)` <= 0.05 & Ii < 0 & bk_dest_borders$S000 >= avg_jobs ~ "HL",
      `Pr(z > 0)` <= 0.05 & Ii < 0 & bk_dest_borders$S000 < avg_jobs ~ "LH"
    )
  )

bk_dest_borders$coType <- bk_lisa_classes$coType %>% tidyr::replace_na("Insignificant")

ggplot(bk_dest_borders) +
  geom_sf(aes(
    fill=coType
  ),
  color = 'lightgrey'
  ) +
  scale_fill_manual(
    values = c("red", "NA","blue"),
    name = "Clusters & \nOutliers"
  ) +
  labs(
    title = "Job count at nta level"
  )
```

### Regression
```{r, message=FALSE}
bk_od_undirected <- bk_od %>%
  ## Only trips that leave the nta
  dplyr::filter(w_nta_code != h_nta_code) %>%
  dplyr::mutate(
      trip = stringr::str_c(
        ifelse(w_nta_code < h_nta_code, w_nta_code, h_nta_code),
        ifelse(w_nta_code > h_nta_code, w_nta_code, h_nta_code)
      )
    ) %>%
  dplyr::group_by(trip) %>%
  dplyr::summarise(
    S000 = sum(S000)
  ) %>%
  unique()

``` 
 
```{r, message=FALSE}
bk_nta_neighbors <- bk_dest_borders %>%
  spdep::poly2nb(c("w_nta_code"))
  
bk_nta_neighbors_map <- vector(mode = "list", length = length(bk_dest$w_nta_code))
for (i in 1:length(bk_nta_neighbors_map)) {
  neighbor_positions <- bk_nta_neighbors[[i]]
  neighbors <- vector(length = length(neighbor_positions))
  for(j in 1:length(neighbors)) {
    neighbors[j] <- bk_dest$w_nta_code[neighbor_positions[[j]]]
  }
  bk_nta_neighbors_map[[i]] <- neighbors
}

bk_dest_neighbors <- tibble::tibble(
  nta_code = bk_dest$w_nta_code,
  neighbors = bk_nta_neighbors_map,
)

bk_od_undirected_neighbors <- bk_od_undirected %>%
  dplyr::mutate(nta_code_a = stringr::str_sub(trip, 1, 4)) %>%
  dplyr::mutate(nta_code_b = stringr::str_sub(trip, 5, 8)) %>%
  dplyr::left_join(bk_dest_neighbors, c("nta_code_a" = "nta_code")) %>%
  dplyr::rowwise() %>%
  dplyr::mutate(are_neighbors = ifelse(nta_code_b %in% neighbors, 1, 0))

sum(bk_od_undirected_neighbors$are_neighbors)

queen_neighbor_model <- lm(S000 ~ are_neighbors, data = bk_od_undirected_neighbors)
plot(queen_neighbor_model)
summary(queen_neighbor_model)
```

